alternate: xiaou
# 是否显示页面加载动画 loading-cat
loader:
  start: true # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画
sidebar:
  # Sidebar Position.
  position: right
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg

widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论

# 页尾全站统计
footer:
  since: 2010
  count: true

# 文章界面统计
post:
  count: true
# bgm
audio:
  - title: 列表1
    list:
      - https://music.163.com/#/playlist?id=2943811283
      - https://music.163.com/#/playlist?id=2297706586
  - title: 列表2
    list:
      - https://music.163.com/#/playlist?id=2031842656

menu:
  home: / || home
  # about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  # links: /links/ || magic
